modLoader="lowcodefml"
loaderVersion="[1,)"
license="MIT"
issueTrackerURL="https://github.com/catter1/Terralith_No_Structures/issues"

[[mods]]
    modId="terralith_no_structures"
    version="1.1"
    displayName="Terralith: No Structures"
    displayURL="https://github.com/catter1/Terralith_No_Structures"
    logoFile="pack.png"
    authors="catter1"
    description="An official add-on to Terralith that removes Terralith's custom structures"

[[dependencies.terralith_no_structures]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.20,)"
    ordering="NONE"
    side="BOTH"
[[dependencies.terralith_no_structures]]
    modId="terralith"
    mandatory=false
    versionRange="[2.0,)"
    ordering="AFTER"
    side="BOTH"